# Generated by Django 2.2.3 on 2019-07-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=256)),
                ('owner', models.CharField(max_length=256)),
                ('segment', models.CharField(blank=True, max_length=256, null=True)),
                ('json_url', models.CharField(blank=True, max_length=256, null=True)),
                ('json_text', models.TextField(blank=True, null=True)),
                ('lif_balance', models.CharField(blank=True, max_length=20, null=True)),
                ('trust_clues', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
